version: "3"
networks:
  my-net:

services:

  zookeeper:
    image: 'zookeeper'
    ports:
      - '2181:2181'
    networks:
      - my-net

  kafka:
    depends_on:
      - zookeeper
    image: 'confluentinc/cp-kafka'
    user: root
    ports:
      - '9092:9092'
    environment:
      # - KAFKA_BROKER_ID=1
      # - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.10.7:9092
      - KAFKA_ZOOKEEPER_CONNECT=192.168.10.7:2181
      # - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    volumes:
      - ./Kafka:/bitnami/kafka
    networks:
      - my-net